name: ci
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2]
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.chunk }}